-- Vorlage / Dokumentation. Die Pipeline führt idempotente Befehle in
-- infra/scripts/ec2-dsql-bootstrap.sh aus (Admin-IAM-Token + psql).
--
-- Aurora DSQL: keine festen Passwörter – Verbindung mit IAM-Token.
--
-- CREATE ROLE verwaltung WITH LOGIN;
-- AWS IAM GRANT verwaltung TO 'arn:aws:iam::ACCOUNT_ID:role/ROLE_NAME';
-- GRANT CONNECT ON DATABASE postgres TO verwaltung;
-- GRANT USAGE, CREATE ON SCHEMA public TO verwaltung;
