
[authentication]
username = "kindergarten"
username_password = "kindergarten"
username_email = "carlos.brockmann@gmx.de"

[webapi]
token_expires_hours = 24
base_url = "http://localhost:5108"
frontend_url = "http://localhost:5173"
verify_ssl = true
