// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Taetigkeitsbericht.Backend.Data;

#nullable disable

namespace Taetigkeitsbericht.Backend.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260810160950_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Taetigkeitsbericht.Backend.Models.Mitarbeiter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Benutzername")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PasswortHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("Benutzername")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("mitarbeiter", (string)null);
                });

            modelBuilder.Entity("Taetigkeitsbericht.Backend.Models.Zeiteintrag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Anmerkung")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateOnly>("Datum")
                        .HasColumnType("date");

                    b.Property<int?>("MandantId")
                        .HasColumnType("integer");

                    b.Property<int>("MitarbeiterId")
                        .HasColumnType("integer");

                    b.Property<TimeOnly?>("Pause2Beginn")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly?>("Pause2Ende")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly?>("PauseBeginn")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly?>("PauseEnde")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("UhrzeitBis")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("UhrzeitVon")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.HasIndex("MitarbeiterId", "Datum");

                    b.ToTable("zeiteintrag", (string)null);
                });

            modelBuilder.Entity("Taetigkeitsbericht.Backend.Models.Zeiteintrag", b =>
                {
                    b.HasOne("Taetigkeitsbericht.Backend.Models.Mitarbeiter", "Mitarbeiter")
                        .WithMany("Zeiteintraege")
                        .HasForeignKey("MitarbeiterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mitarbeiter");
                });

            modelBuilder.Entity("Taetigkeitsbericht.Backend.Models.Mitarbeiter", b =>
                {
                    b.Navigation("Zeiteintraege");
                });
#pragma warning restore 612, 618
        }
    }
}
